// 'use client'

import type { Metadata } from 'next'
// import './globals.css'
// import { ThemeProvider } from '@/providers/theme/index'

import '@/styles/globalTheme.css'
// import 'src/styles/globalTheme.css'

import ThemeProvider from '@/context/ThemeProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>{/* <OptimizeTypeKit projectId="ygf6mjq" /> */}</head>
      <body>
        <ThemeProvider>
          {children}
          {/* <ThemeProvider defaultTheme="dark">{children}</ThemeProvider> */}
        </ThemeProvider>
      </body>
    </html>
  )
}
